import type {
  Band,
  ExtractionDetail,
  ExtractionReviewRecord,
  ReviewUnit,
  SpanAnnotationRecord,
} from "./types";
import { isBand, unitKey } from "./types";
import { appendLine, isS3Configured, listPaths, localPath, readText, writeJson } from "./storage";

// Static index generated by `npm run prepare-data`; small enough to bundle.
import reviewUnits from "./review-units.json";

// Re-exported so route handlers can branch on the backend without importing the
// storage module directly.
export { isS3Configured } from "./storage";

// Repo-relative, so the same strings work on disk and as S3 keys.
const JSONL_PATH = "annotations/chunk_span_annotations.jsonl";
const S3_ROOT = "chunk_annotations";

export function outputLocation(): string {
  return isS3Configured() ? `${S3_ROOT}/` : JSONL_PATH;
}

/**
 * Annotator names are free text typed by a person. Compare them loosely -- "MB",
 * "mb" and " mb " are the same annotator -- and slugify before putting one in a
 * key path.
 */
export function normaliseAnnotator(annotator: string): string {
  return annotator.trim().toLowerCase().replace(/\s+/g, " ");
}

export function annotatorSlug(annotator: string): string {
  return normaliseAnnotator(annotator)
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Where one judgement lives in S3 mode.
 *
 * The band is part of the path so a ListObjectsV2 on the annotator's prefix yields
 * both the unit identity and its stratum without fetching a single object -- which
 * is what makes the per-band tally cheap. A unit belongs to exactly one band for a
 * given pipeline run, so this never splits one unit across two keys.
 *
 * One object per unit, so a re-annotation overwrites rather than appending a
 * duplicate, and two annotators submitting at once cannot clobber each other.
 */
export function recordKey(record: SpanAnnotationRecord): string {
  return (
    `${S3_ROOT}/${annotatorSlug(record.annotator)}/${record.band}/` +
    `${record.source}/${record.engine}/${record.document_id}/` +
    `${record.chunk_id}/${record.concept_id}.json`
  );
}

export async function appendSpanRecord(record: SpanAnnotationRecord): Promise<void> {
  // Let write failures propagate -- the caller must surface them so a submission
  // is never silently lost.
  if (isS3Configured()) {
    await writeJson(recordKey(record), record);
    return;
  }
  await appendLine(JSONL_PATH, JSON.stringify(record));
}

interface DoneUnit {
  key: string;
  band: Band | null;
}

/**
 * Distinct units this annotator has submitted, with the band each was drawn from.
 *
 * S3: parsed straight out of the keys, no object reads. Local: read back from the
 * append-only JSONL, where a re-annotated unit appears more than once, so the last
 * row wins.
 */
async function getDoneUnits(annotator: string): Promise<DoneUnit[]> {
  if (isS3Configured()) {
    const prefix = `${S3_ROOT}/${annotatorSlug(annotator)}/`;
    const paths = await listPaths(prefix);
    const out: DoneUnit[] = [];
    for (const p of paths) {
      if (!p.endsWith(".json")) continue;
      // band/source/engine/documentId/chunkId/conceptId.json
      const parts = p.slice(prefix.length, -".json".length).split("/");
      if (parts.length !== 6) continue;
      const [band, source, engine, documentId, chunkId, conceptId] = parts;
      out.push({
        key: unitKey({ source, engine, documentId, chunkId }, conceptId),
        band: isBand(band) ? band : null,
      });
    }
    return out;
  }

  let raw: string;
  try {
    raw = await readText(JSONL_PATH);
  } catch {
    return []; // nothing submitted yet
  }

  const who = normaliseAnnotator(annotator);
  const latest = new Map<string, Band | null>();
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    let r: SpanAnnotationRecord;
    try {
      r = JSON.parse(line) as SpanAnnotationRecord;
    } catch {
      continue; // skip malformed lines rather than failing the whole lookup
    }
    if (normaliseAnnotator(r.annotator) !== who) continue;
    latest.set(
      unitKey(
        { source: r.source, engine: r.engine, documentId: r.document_id, chunkId: r.chunk_id },
        r.concept_id
      ),
      isBand(r.band) ? r.band : null
    );
  }

  const out: DoneUnit[] = [];
  latest.forEach((band, key) => out.push({ key, band }));
  return out;
}

/** Unit keys this annotator has already submitted, de-duplicated. */
export async function getCompletedUnits(annotator: string): Promise<string[]> {
  const seen = new Set<string>();
  for (const u of await getDoneUnits(annotator)) seen.add(u.key);
  return Array.from(seen);
}

/** How many distinct units this annotator has done in each band. */
export async function getBandTally(annotator: string): Promise<Record<string, number>> {
  const byKey = new Map<string, Band | null>();
  for (const u of await getDoneUnits(annotator)) byKey.set(u.key, u.band);

  const tally: Record<string, number> = {};
  byKey.forEach((band) => {
    if (band) tally[band] = (tally[band] ?? 0) + 1;
  });
  return tally;
}

// ══════════════════════════════════════════════════════════════════════════════
// Extraction review
// ══════════════════════════════════════════════════════════════════════════════
// Restored from commit acd0448, rewired onto lib/storage.ts so the review view
// works from S3 exactly like the annotation view. The S3 key layout is unchanged
// from the original -- reviews/{reviewer}/{run}/{document}/{concept}.json -- so
// judgements submitted before the rework are still found.

/** Identifies one review unit. No part contains a slash, so this round-trips. */
export function reviewKey(run: string, documentId: string, conceptId: string): string {
  return `${run}/${documentId}/${conceptId}`;
}

export function getReviewUnits(): ReviewUnit[] {
  return reviewUnits as ReviewUnit[];
}

/**
 * Extraction detail is ~7 MB, so it is fetched once per process and held. Read
 * through the storage layer, which means it resolves from the repo working tree
 * locally and from the bucket when S3_BUCKET_NAME is set.
 */
const REVIEW_EXTRACTIONS_PATH = "annotation_ui/data/review-extractions.json";
let extractionPromise: Promise<Record<string, ExtractionDetail>> | null = null;

export function getExtractionDetail(
  run: string,
  documentId: string
): Promise<ExtractionDetail | null> {
  if (!extractionPromise) {
    extractionPromise = readText(REVIEW_EXTRACTIONS_PATH)
      .then((raw) => JSON.parse(raw) as Record<string, ExtractionDetail>)
      .catch((err) => {
        extractionPromise = null; // let a later request retry a transient failure
        throw err;
      });
  }
  return extractionPromise.then((cache) => cache[`${run}/${documentId}`] ?? null);
}

const REVIEWS_S3_ROOT = "reviews";
const REVIEWS_JSONL_PATH = "annotations/extraction_reviews.jsonl";

export function reviewRecordKey(record: ExtractionReviewRecord): string {
  return (
    `${REVIEWS_S3_ROOT}/${annotatorSlug(record.reviewer)}/` +
    `${record.run}/${record.document_id}/${record.concept_id}.json`
  );
}

export async function submitReview(record: ExtractionReviewRecord): Promise<void> {
  // As with annotations: let failures propagate rather than lose a judgement.
  if (isS3Configured()) {
    await writeJson(reviewRecordKey(record), record);
    return;
  }
  await appendLine(REVIEWS_JSONL_PATH, JSON.stringify(record));
}

/**
 * Review keys this reviewer has already submitted, de-duplicated.
 *
 * S3: parsed out of the object keys, no fetches. Local: read back from the
 * append-only JSONL, where a re-reviewed unit appears more than once.
 */
export async function getCompletedReviews(reviewer: string): Promise<string[]> {
  if (isS3Configured()) {
    const prefix = `${REVIEWS_S3_ROOT}/${annotatorSlug(reviewer)}/`;
    const keys = new Set<string>();
    for (const p of await listPaths(prefix)) {
      if (!p.endsWith(".json")) continue;
      const rel = p.slice(prefix.length, -".json".length);
      if (rel.split("/").length === 3) keys.add(rel);
    }
    return Array.from(keys);
  }

  let raw: string;
  try {
    raw = await readText(REVIEWS_JSONL_PATH);
  } catch {
    return []; // nothing reviewed yet
  }

  const who = normaliseAnnotator(reviewer);
  const keys = new Set<string>();
  for (const line of raw.split("\n")) {
    if (!line.trim()) continue;
    try {
      const r = JSON.parse(line) as ExtractionReviewRecord;
      if (normaliseAnnotator(r.reviewer) !== who) continue;
      keys.add(reviewKey(r.run, r.document_id, r.concept_id));
    } catch {
      // Skip malformed lines rather than failing the whole progress lookup.
    }
  }
  return Array.from(keys);
}

// ── PDF access (the review view shows the source contract) ────────────────────

/**
 * A presigned URL the browser fetches directly, rather than proxying the bytes
 * through this server -- some contracts are 25 MB.
 */
export async function getPDFPresignedUrl(source: string, filename: string): Promise<string> {
  const { GetObjectCommand, S3Client } = await import("@aws-sdk/client-s3");
  const { getSignedUrl } = await import("@aws-sdk/s3-request-presigner");
  const bucket = process.env.S3_BUCKET_NAME;
  if (!bucket) throw new Error("S3_BUCKET_NAME is not set");
  const prefix = (process.env.S3_PREFIX ?? "").replace(/^\/+|\/+$/g, "");
  const key = `${prefix ? prefix + "/" : ""}cbas/${source}/${filename}`;
  const client = new S3Client({ region: process.env.AWS_REGION ?? "us-east-1" });
  return getSignedUrl(client, new GetObjectCommand({ Bucket: bucket, Key: key }), {
    expiresIn: 900,
  });
}

/** Local-disk fallback for the PDF panel: data/cbas/{source}/{filename}. */
export function getCBAFilePath(source: string, filename: string): string {
  return localPath(`data/cbas/${source}/${filename}`);
}
