import fs from "fs";
import path from "path";
import { S3Client, GetObjectCommand } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import type { CBA, Provision, AnnotationRecord } from "./types";

// Static manifests generated by `npm run prepare-data`
import cbaManifest from "./cba-manifest.json";
import provisionList from "./provisions.json";

// ── S3 client (only constructed when bucket is configured) ───────────────────
const BUCKET = process.env.S3_BUCKET_NAME;
const REGION = process.env.AWS_REGION ?? "us-east-1";
let s3: S3Client | null = null;
function getS3(): S3Client {
  if (!s3) s3 = new S3Client({ region: REGION });
  return s3;
}

// ── CBA list ─────────────────────────────────────────────────────────────────
export function getAllCBAs(): CBA[] {
  return cbaManifest as CBA[];
}

export function getRandomCBA(): CBA {
  const all = getAllCBAs();
  return all[Math.floor(Math.random() * all.length)];
}

// ── Provision dictionary ─────────────────────────────────────────────────────
export function getAllProvisions(): Provision[] {
  return provisionList as Provision[];
}

export function getRandomProvisions(n: number): Provision[] {
  const all = getAllProvisions();
  const fixed = all.find((p) => p.conceptId === "C_WAGE_BASE_RATE")!;
  const rest = all.filter((p) => p.conceptId !== "C_WAGE_BASE_RATE");
  // Fisher-Yates shuffle on the remaining provisions
  for (let i = rest.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [rest[i], rest[j]] = [rest[j], rest[i]];
  }
  return [fixed, ...rest.slice(0, n - 1)];
}

// ── PDF access ───────────────────────────────────────────────────────────────

export async function getPDFPresignedUrl(source: string, filename: string): Promise<string> {
  const key = `cbas/${source}/${filename}`;
  const command = new GetObjectCommand({ Bucket: BUCKET!, Key: key });
  return getSignedUrl(getS3(), command, { expiresIn: 900 });
}

export function getCBAFilePath(source: string, filename: string): string {
  const REPO_ROOT = path.resolve(process.cwd(), "..");
  const CBAS_DIR = path.join(REPO_ROOT, "data", "cbas");
  const resolved = path.resolve(CBAS_DIR, source, filename);
  if (!resolved.startsWith(CBAS_DIR + path.sep)) throw new Error("Invalid path");
  return resolved;
}

export function isS3Configured(): boolean {
  return !!BUCKET;
}

// ── Annotation output (JSONL) ─────────────────────────────────────────────────
const REPO_ROOT = path.resolve(process.cwd(), "..");
const ANNOTATIONS_PATH = path.join(REPO_ROOT, "data", "annotations", "human_annotations.jsonl");

export function appendAnnotationRecord(record: AnnotationRecord): void {
  try {
    const dir = path.dirname(ANNOTATIONS_PATH);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.appendFileSync(ANNOTATIONS_PATH, JSON.stringify(record) + "\n", "utf-8");
  } catch (err) {
    console.error("[submit] Could not write annotation to disk:", err);
  }
}
