import fs from "fs";
import path from "path";
import {
  S3Client,
  GetObjectCommand,
  PutObjectCommand,
  ListObjectsV2Command,
} from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import type {
  CBA,
  Provision,
  AnnotationRecord,
  ProvisionSchema,
  ReviewUnit,
  ExtractionDetail,
  ExtractionReviewRecord,
} from "./types";

// Static manifests generated by `npm run prepare-data`
import cbaManifest from "./cba-manifest.json";
import provisionList from "./provisions.json";
import provisionSchemas from "./provision-schemas.json";
import reviewUnits from "./review-units.json";

const SCHEMAS = provisionSchemas as Record<string, ProvisionSchema>;

// ── S3 client (only constructed when bucket is configured) ───────────────────
const BUCKET = process.env.S3_BUCKET_NAME;
const REGION = process.env.AWS_REGION ?? "us-east-1";
let s3: S3Client | null = null;
function getS3(): S3Client {
  if (!s3) s3 = new S3Client({ region: REGION });
  return s3;
}

// ── Document id ──────────────────────────────────────────────────────────────
// The stem of the original PDF, used as the annotation object's basename.
// e.g. "3693ABBYY.pdf" → "3693ABBYY"
export function documentId(filename: string): string {
  return filename.replace(/\.[^./]+$/, "");
}

// ── CBA list ─────────────────────────────────────────────────────────────────
export function getAllCBAs(): CBA[] {
  return cbaManifest as CBA[];
}

export function getRandomCBA(): CBA {
  const all = getAllCBAs();
  return all[Math.floor(Math.random() * all.length)];
}

export function getRandomCBAExcluding(excludeKeys: string[]): CBA | null {
  const excluded = new Set(excludeKeys);
  const available = getAllCBAs().filter(
    (c) => !excluded.has(`${c.source}/${documentId(c.filename)}`)
  );
  if (available.length === 0) return null;
  return available[Math.floor(Math.random() * available.length)];
}

// ── Provision dictionary ─────────────────────────────────────────────────────
export function getAllProvisions(): Provision[] {
  return provisionList as Provision[];
}

// Only "core"-tier concepts are ever presented for annotation.
export function getCoreProvisions(): Provision[] {
  return getAllProvisions().filter(
    (p) => SCHEMAS[p.conceptId]?.meta?.priority_tier === "core"
  );
}

export function getRandomProvisions(n: number): Provision[] {
  const all = getCoreProvisions();
  const fixed = all.find((p) => p.conceptId === "C_WAGE_BASE_RATE")!;
  const rest = all.filter((p) => p.conceptId !== "C_WAGE_BASE_RATE");
  // Fisher-Yates shuffle on the remaining provisions
  for (let i = rest.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [rest[i], rest[j]] = [rest[j], rest[i]];
  }
  return [fixed, ...rest.slice(0, n - 1)];
}

// ── PDF access ───────────────────────────────────────────────────────────────

export async function getPDFPresignedUrl(source: string, filename: string): Promise<string> {
  const key = `cbas/${source}/${filename}`;
  const command = new GetObjectCommand({ Bucket: BUCKET!, Key: key });
  return getSignedUrl(getS3(), command, { expiresIn: 900 });
}

export function getCBAFilePath(source: string, filename: string): string {
  const REPO_ROOT = path.resolve(process.cwd(), "..");
  const CBAS_DIR = path.join(REPO_ROOT, "data", "cbas");
  const resolved = path.resolve(CBAS_DIR, source, filename);
  if (!resolved.startsWith(CBAS_DIR + path.sep)) throw new Error("Invalid path");
  return resolved;
}

export function isS3Configured(): boolean {
  return !!BUCKET;
}

// ── Annotation output — S3 (production) ──────────────────────────────────────

export async function writeAnnotationToS3(
  prolificPid: string,
  record: AnnotationRecord
): Promise<void> {
  const key = `annotations/${prolificPid}/${record.cba_source}/${documentId(record.cba_filename)}.json`;
  await getS3().send(
    new PutObjectCommand({
      Bucket: BUCKET!,
      Key: key,
      Body: JSON.stringify(record),
      ContentType: "application/json",
    })
  );
}

export async function getCompletedCBAsForPID(prolificPid: string): Promise<string[]> {
  const prefix = `annotations/${prolificPid}/`;
  const keys: string[] = [];
  let continuationToken: string | undefined;

  do {
    const response = await getS3().send(
      new ListObjectsV2Command({
        Bucket: BUCKET!,
        Prefix: prefix,
        ContinuationToken: continuationToken,
      })
    );
    for (const obj of response.Contents ?? []) {
      if (!obj.Key) continue;
      // Strip "annotations/{pid}/" prefix and ".json" suffix → "source/document_id"
      const rel = obj.Key.slice(prefix.length);
      const cbaKey = rel.endsWith(".json") ? rel.slice(0, -5) : rel;
      if (cbaKey) keys.push(cbaKey);
    }
    continuationToken = response.IsTruncated ? response.NextContinuationToken : undefined;
  } while (continuationToken);

  return keys;
}

// ── Annotation output — local disk (dev fallback) ─────────────────────────────
const REPO_ROOT = path.resolve(process.cwd(), "..");
const ANNOTATIONS_PATH = path.join(REPO_ROOT, "data", "annotations", "human_annotations.jsonl");

export function appendAnnotationRecord(record: AnnotationRecord): void {
  // Let write failures propagate — the caller must surface them so an
  // annotation is never silently lost on a failed local write.
  const dir = path.dirname(ANNOTATIONS_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.appendFileSync(ANNOTATIONS_PATH, JSON.stringify(record) + "\n", "utf-8");
}

// ── Extraction review ─────────────────────────────────────────────────────────

/**
 * Identifies one review unit. Neither `run` nor `documentId` nor `conceptId`
 * contains a slash, so this round-trips through an S3 key path unambiguously.
 */
export function reviewKey(run: string, documentId: string, conceptId: string): string {
  return `${run}/${documentId}/${conceptId}`;
}

/** Reviewer names are free text; slugify before putting one in a storage path. */
export function reviewerSlug(reviewer: string): string {
  return reviewer.trim().toLowerCase().replace(/[^a-z0-9._-]+/g, "-").replace(/^-+|-+$/g, "");
}

export function getReviewUnits(): ReviewUnit[] {
  return reviewUnits as ReviewUnit[];
}

// Extraction detail is ~7 MB and lives outside lib/ so it is never bundled into
// the client. Read once and hold it — re-reading per request would be wasteful.
const REVIEW_EXTRACTIONS_PATH = path.join(process.cwd(), "data", "review-extractions.json");
let extractionCache: Record<string, ExtractionDetail> | null = null;

export function getExtractionDetail(run: string, documentId: string): ExtractionDetail | null {
  if (!extractionCache) {
    if (!fs.existsSync(REVIEW_EXTRACTIONS_PATH)) return null;
    extractionCache = JSON.parse(fs.readFileSync(REVIEW_EXTRACTIONS_PATH, "utf-8"));
  }
  return extractionCache![`${run}/${documentId}`] ?? null;
}

// ── Review output — S3 (production) ──────────────────────────────────────────

export async function writeReviewToS3(record: ExtractionReviewRecord): Promise<void> {
  const key =
    `reviews/${reviewerSlug(record.reviewer)}/` +
    `${record.run}/${record.document_id}/${record.concept_id}.json`;
  await getS3().send(
    new PutObjectCommand({
      Bucket: BUCKET!,
      Key: key,
      Body: JSON.stringify(record),
      ContentType: "application/json",
    })
  );
}

export async function getCompletedReviewsForReviewer(reviewer: string): Promise<string[]> {
  const prefix = `reviews/${reviewerSlug(reviewer)}/`;
  const keys: string[] = [];
  let continuationToken: string | undefined;

  do {
    const response = await getS3().send(
      new ListObjectsV2Command({
        Bucket: BUCKET!,
        Prefix: prefix,
        ContinuationToken: continuationToken,
      })
    );
    for (const obj of response.Contents ?? []) {
      if (!obj.Key) continue;
      // Strip "reviews/{reviewer}/" and ".json" → "{run}/{documentId}/{conceptId}"
      const rel = obj.Key.slice(prefix.length);
      const unitKey = rel.endsWith(".json") ? rel.slice(0, -5) : rel;
      if (unitKey) keys.push(unitKey);
    }
    continuationToken = response.IsTruncated ? response.NextContinuationToken : undefined;
  } while (continuationToken);

  return keys;
}

// ── Review output — local disk (dev fallback) ────────────────────────────────

const REVIEWS_PATH = path.join(REPO_ROOT, "data", "annotations", "extraction_reviews.jsonl");

export function appendReviewRecord(record: ExtractionReviewRecord): void {
  // As with annotations: let failures propagate rather than lose a judgement.
  const dir = path.dirname(REVIEWS_PATH);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.appendFileSync(REVIEWS_PATH, JSON.stringify(record) + "\n", "utf-8");
}

/**
 * Completed unit keys for one reviewer, read back from the local JSONL. The file
 * is append-only, so a re-reviewed unit appears more than once; de-duplicate.
 */
export function getLocalCompletedReviews(reviewer: string): string[] {
  if (!fs.existsSync(REVIEWS_PATH)) return [];
  const slug = reviewerSlug(reviewer);
  const keys = new Set<string>();
  for (const line of fs.readFileSync(REVIEWS_PATH, "utf-8").split("\n")) {
    if (!line.trim()) continue;
    try {
      const r = JSON.parse(line) as ExtractionReviewRecord;
      if (reviewerSlug(r.reviewer) !== slug) continue;
      keys.add(reviewKey(r.run, r.document_id, r.concept_id));
    } catch {
      // Skip malformed lines rather than failing the whole progress lookup.
    }
  }
  return Array.from(keys);
}
